apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-pd-standard
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
